version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: meu_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
networks:
  default:
    driver: bridge
